//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Feedbacks1 = new HashSet<Feedback>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile { get; set; }
        public int UserTypeId { get; set; }
        public string Password { get; set; }
        public string NewPassword { get; set; }
        public string ConformPassword { get; set; }
        public string UserPhoto { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsFirstLogin { get; set; }
        public string HIgestQualification { get; set; }
        public string AboutInfo { get; set; }
        public bool IsActive { get; set; }
        public string Specialist { get; set; }
    
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<Feedback> Feedbacks1 { get; set; }
    }
}
